insert into Clientes(ID, Nome)
values
('Adalberto Martins da Silva')
('Adan Roger Guimarães Dias')
('Adão Walter Gomes de Sousa')
('Adelson Fernandes Sena')
('Ademir Augusto Simões')
('Ademir Borges dos Santos')
('Adilio José da Silva Santos')
('Adriana Ferreira de Lima Teodoro')
('Adriano Bezerra Apolinario')
('Adriano Heleno Basso')
('Adriano Lourenço do Rego')
('Adriano Matos Santos')
('Adriano Pires Caetano')
('Adriano Prada de Campos')
('Adriel Alberto dos Santos')
('Agner Vinicius Marques de Camargo')
('Agrinaldo Ferreira Soares')
('Alan Jhonnes Banlian da Silva e Sá')
('Alberto Ramos Rodrigues')
('Alcides José Ramos')
('Aldemir SantAna dos Santos')
('Aleksandro Marcelo da Silva')
('Alessandro Martins Silva')
('Alessandro Sanches')
('Alex dos Reis de Jesus')
('Alex Ferreira Soares')
('Alex Sandro Oliveira')
('Alex Souza Farias')
('Alexandra de Lima Silva')
('Alexandre Clemente da Costa')